version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./app
    expose:
      - "8501"
    networks:
      - app-network

networks:
  app-network:
